spring:
  application:
    name: IDENTITY-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ASP-springapigatewayservices-a676

server:
  port: 9898
